# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzFTSFmf1UVU-diHlRsPbvaAVCIprnzY
"""

!pip install speechbrain==0.5.16
!pip install faster_whisper
!pip install pyannote.audio

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

import librosa
import traceback
import torch
import whisper
import datetime
from pathlib import Path
import pandas as pd
import re
import time
import os
import numpy as np
from sklearn.cluster import AgglomerativeClustering
from pyannote.audio.pipelines.speaker_verification import PretrainedSpeakerEmbedding
from pyannote.audio import Audio
from pyannote.core import Segment
from scipy.spatial.distance import cdist

audio_file_path="/content/Audio.wav"
Audio("/content/Audio.wav")

!ffmeg-i"{audio_file_path}"-ar 16000-ac 1-c:a pcm_s161e"{audio_file_path[:-4]}.wav"

import librosa
import traceback
from faster_whisper import WhisperModel
import torch
import datetime
import time
import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering
from pyannote.audio.pipelines.speaker_verification import PretrainedSpeakerEmbedding
from pyannote.audio import Audio
from pyannote.core import Segment

# Whisper model options
whisper_models = ["tiny", "base", "small", "medium", "large-v1", "large-v2"]

# Load speaker embedding model
embedding_model = PretrainedSpeakerEmbedding(
    "speechbrain/spkrec-ecapa-voxceleb",
    device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
)

# Convert seconds to HH:MM:SS

def convert_time(secs):
    return datetime.timedelta(seconds=round(secs))

# Main function
def speech_to_text(audio_file, whisper_model_name):
    model = WhisperModel(whisper_model_name, compute_type="int8")
    time_start = time.time()

    try:
        # Load audio
        audio_data, sample_rate = librosa.load(audio_file, mono=True, sr=16000)
        duration = len(audio_data) / sample_rate

        # Transcribe
        options = dict(language='en', beam_size=5, best_of=5)
        transcribe_options = dict(task="transcribe", **options)
        segments_raw, info = model.transcribe(audio_file, **transcribe_options)

        # Convert segments to OpenAI format
        segments = []
        for segment_chunk in segments_raw:
            chunk = {
                "start": segment_chunk.start,
                "end": segment_chunk.end,
                "text": segment_chunk.text
            }
            segments.append(chunk)
            print(segment_chunk.start, segment_chunk.end, segment_chunk.text)

    except Exception as e:
        traceback.print_exc()
        raise RuntimeError("Error converting audio to text") from e

    try:
        # Embedding helper function
        def segment_embedding(segment):
            try:
                audio = Audio()
                start = segment["start"]
                end = min(duration, segment["end"])
                clip = Segment(start, end)
                waveform, sample_rate = audio.crop(audio_file, clip)

                # Ensure mono-channel audio
                if waveform.shape[0] > 1:
                    waveform = waveform.mean(axis=0, keepdims=True)

                embeddings = embedding_model(waveform[None])
                return embeddings[0]
            except Exception as e:
                traceback.print_exc()
                raise RuntimeError("Error during segment embedding") from e

        # Create all segment embeddings
        embeddings = np.zeros((len(segments), 192))
        for i, segment in enumerate(segments):
            embeddings[i] = segment_embedding(segment)
        embeddings = np.nan_to_num(embeddings)

        # Assign speaker labels
        best_num_speakers = 2
        clustering = AgglomerativeClustering(n_clusters=best_num_speakers).fit(embeddings)
        labels = clustering.labels_

        for i in range(len(segments)):
            segments[i]["speaker"] = 'SPEAKER ' + str(labels[i] + 1)

        # Create structured output
        rows = []
        for segment in segments:
            rows.append({
                "Start": convert_time(segment["start"]),
                "End": convert_time(segment["end"]),
                "Speaker": segment["speaker"],
                "Text": segment["text"]
            })

        # Save to CSV
        df_results = pd.DataFrame(rows)
        save_path = "/content/transcription_results.csv"
        df_results.to_csv(save_path, index=False)

        return df_results, save_path

    except Exception as e:
        print("Exception occurred:", e)
        raise RuntimeError("Error running inference with local model") from e

# Audio file and whisper model
audio_file = "/content/Audio.wav"  # ✅ Make sure file exists
selected_whisper_model = "base"

# Run transcription
transcription_results, save_path = speech_to_text(audio_file, selected_whisper_model)

# Output
print(transcription_results)
print(f"Transcription results saved at: {save_path}")