# -*- coding: utf-8 -*-
"""KMeans Diarization Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKVnGOAwqcRBk3GDdaFDtzHk_bOUTbcQ

## Speaker Diarization using clustering algorithms

**✨ Importing datasets ✨**
"""

!pip install opendatasets

"""{"username":"anshuvairagade7", "Key":"b906e2144101283a6f10132731a7f6d1"}"""

# {"username":"anshuvairagade7", "Key":"b906e2144101283a6f10132731a7f6d1"}
import opendatasets as od
od.download("https://www.kaggle.com/datasets/wiradkp/minispeakerdiarization2")
od.download("https://www.kaggle.com/datasets/wiradkp/mini-speech-diarization")

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

"""
**✨ Importing necessary libraries ✨**
"""

import numpy as np
import pandas as pd
import os
from pathlib import Path
import librosa
from pydub import AudioSegment
import matplotlib.pyplot as plt
from random import choice, randint, shuffle
from IPython.display import Audio, display
from tqdm import tqdm
import uuid
import torch
from transformers import Wav2Vec2Processor, Wav2Vec2Model
import torchaudio

import whisper
model = whisper.load_model("medium")
print("Whisper installed successfully!")

from IPython.display import Audio, display
Audio("/content/mini-speech-diarization/dataset/valid/professor/audio_8.wav")

!whisper "/content/mini-speech-diarization/dataset/valid/professor/audio_8.wav"

""".

.
"""

# Install required packages
!pip install -q speechbrain torchaudio numpy

import numpy as np
import torch
import torchaudio
from speechbrain.pretrained import EncoderClassifier
from tqdm import tqdm

class XVectorEmbedder:
    def __init__(self, device='cuda' if torch.cuda.is_available() else 'cpu'):
        self.device = device
        self.classifier = EncoderClassifier.from_hparams(
            source="speechbrain/spkrec-xvect-voxceleb",
            savedir="/content/pretrained_models/xvector",
            run_opts={"device": self.device}
        )
        self.target_sample_rate = 16000
        self.min_duration = 1.0

    def _preprocess_audio(self, waveform, sample_rate):

        if sample_rate != self.target_sample_rate:
            resampler = torchaudio.transforms.Resample(
                orig_freq=sample_rate,
                new_freq=self.target_sample_rate
            )
            waveform = resampler(waveform)


        waveform = waveform.mean(dim=0, keepdim=True) if waveform.shape[0] > 1 else waveform
        current_duration = waveform.shape[1] / self.target_sample_rate


        if current_duration < self.min_duration:
            pad_size = int((self.min_duration - current_duration) * self.target_sample_rate)
            waveform = torch.nn.functional.pad(waveform, (0, pad_size))

        return waveform.to(self.device)

    def create_embeddings(self, audio_paths):
        """Process audio files from Colab directory structure"""
        embeddings = []
        for path in tqdm(audio_paths, desc="Processing audio files"):
            try:
                waveform, sample_rate = torchaudio.load(path)
                waveform = self._preprocess_audio(waveform, sample_rate)
                with torch.no_grad():
                    emb = self.classifier.encode_batch(waveform)
                    emb = emb.squeeze().cpu().numpy()
                embeddings.append(emb)
            except Exception as e:
                print(f"Error processing {path}: {str(e)}")
                continue

        return np.array(embeddings)


embedder = XVectorEmbedder()


train_sample1 = [
    "/content/minispeakerdiarization2/dataset/train/anthropology_professor/audio_1.wav",
    "/content/minispeakerdiarization2/dataset/train/biology_professor/audio_1.wav",
    "/content/minispeakerdiarization2/dataset/train/customer/audio_1.wav",
    "/content/minispeakerdiarization2/dataset/train/literature_professor/audio_1.wav",
    "/content/minispeakerdiarization2/dataset/train/physics_professor/audio_1.wav",
    "/content/minispeakerdiarization2/dataset/train/store_clerk/audio_1.wav"
]

# Generate embeddings
embeddings = embedder.create_embeddings(train_sample1)


np.save("/content/speaker_embeddings.npy", embeddings)
print(f"Embeddings saved to /content/speaker_embeddings.npy")
print(f"Embedding shape: {embeddings.shape}")


embeddings_normalized = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

print(type(embeddings_normalized))

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import joblib

# Load the saved embeddings
embeddings = np.load("/content/speaker_embeddings.npy")

# Normalize embeddings
scaler = StandardScaler()
embeddings_normalized = scaler.fit_transform(embeddings)

print(type(embeddings))
print(embeddings)
print(embeddings.shape)

"""**Model Training**"""

# Train KMeans model
n_speakers = 6
kmeans = KMeans(n_clusters=n_speakers, random_state=42)
cluster_labels = kmeans.fit_predict(embeddings_normalized)

# Save the trained model
joblib.dump(kmeans, '/content/speaker_clustering_model.pkl')
print("Model saved to /content/speaker_clustering_model.pkl")

# Visualization using PCA
pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings_normalized)

plt.figure(figsize=(10, 8))
scatter = plt.scatter(embeddings_2d[:, 0], embeddings_2d[:, 1], c=cluster_labels, cmap='viridis', alpha=0.8)
plt.title('Speaker Clustering Visualization')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')

# Annotate with speaker labels from file paths
speaker_labels = [path.split('/')[-2] for path in train_sample1]
for i, label in enumerate(speaker_labels):
    plt.annotate(label, (embeddings_2d[i, 0], embeddings_2d[i, 1]), fontsize=8)

plt.colorbar(scatter, label='Cluster')
plt.savefig('/content/clustering_visualization.png')
plt.show()

# Print unique speakers detected
unique_clusters = np.unique(cluster_labels)
print(f"Number of unique speakers detected: {len(unique_clusters)}")


print("\nCluster-Speaker Mapping:")
for cluster in unique_clusters:
    cluster_indices = np.where(cluster_labels == cluster)[0]
    speakers_in_cluster = [speaker_labels[i] for i in cluster_indices]
    print(f"Cluster {cluster}: {', '.join(set(speakers_in_cluster))}")

"""# Training on Mini Speech Diarization Dataset"""

train_sample2 = [
    "/content/mini-speech-diarization/dataset/train/professor/audio_1.wav",
    "/content/mini-speech-diarization/dataset/train/professor/audio_2.wav",
    "/content/mini-speech-diarization/dataset/train/professor/audio_3.wav",
    "/content/mini-speech-diarization/dataset/train/professor/audio_4.wav",
    "/content/mini-speech-diarization/dataset/train/professor/audio_5.wav",
    "/content/mini-speech-diarization/dataset/train/professor/audio_6.wav",
    "/content/mini-speech-diarization/dataset/train/professor/audio_7.wav",
    "/content/mini-speech-diarization/dataset/train/professor/audio_8.wav",
    "/content/mini-speech-diarization/dataset/train/student/audio_1.wav",
    "/content/mini-speech-diarization/dataset/train/student/audio_2.wav",
    "/content/mini-speech-diarization/dataset/train/student/audio_3.wav",
    "/content/mini-speech-diarization/dataset/train/student/audio_4.wav",
    "/content/mini-speech-diarization/dataset/train/student/audio_5.wav",
    "/content/mini-speech-diarization/dataset/train/student/audio_6.wav",
]

# Generate embeddings
embeddings2 = embedder.create_embeddings(train_sample2)

# Save embeddings for clustering
np.save("/content/speaker_embeddings2.npy", embeddings2)
print(f"Embeddings saved to /content/speaker_embeddings2.npy")
print(f"Embedding shape: {embeddings2.shape}")

embeddings_normalized2 = embeddings2 / np.linalg.norm(embeddings2, axis=1, keepdims=True)

# Load the saved embeddings
embeddings2 = np.load("/content/speaker_embeddings2.npy")

# Normalize embeddings
scaler = StandardScaler()
embeddings_normalized2 = scaler.fit_transform(embeddings2)

# Train KMeans model
n_speakers = 2
kmeans = KMeans(n_clusters=n_speakers, random_state=42)
cluster_labels = kmeans.fit_predict(embeddings_normalized2)

import numpy as np


unique_clusters = np.unique(cluster_labels)

# Map cluster IDs to roles
cluster_role_map = {
    unique_clusters[0]: "Professor",
    unique_clusters[1]: "Student"
}

print("Cluster ID → Assigned Role:")
for cluster_id in unique_clusters:
    print(f"  Cluster {cluster_id}: {cluster_role_map[cluster_id]}")

role_labels = [cluster_role_map[cluster] for cluster in cluster_labels]

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# PCA projection
pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings_normalized2)
centroids_2d = pca.transform(kmeans.cluster_centers_)

plt.figure(figsize=(10, 8))
scatter = plt.scatter(
    embeddings_2d[:, 0],
    embeddings_2d[:, 1],
    c=cluster_labels,
    cmap='viridis',
    alpha=0.8,
    edgecolor='k'
)

for i, role in enumerate(role_labels):
    plt.annotate(role, (embeddings_2d[i, 0], embeddings_2d[i, 1]), fontsize=8, alpha=0.7)

plt.scatter(
    centroids_2d[:, 0],
    centroids_2d[:, 1],
    marker='X',
    s=200,
    c='red',
    label='Centroids'
)

plt.title('KMeans Clustering with Role Labels (PCA Projection)')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend()
plt.colorbar(scatter, label='Cluster ID')
plt.tight_layout()
plt.show()

"""# ----------- TRAINING PHASE (Save Full Pipeline) -----------"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from pathlib import Path
import librosa
from pydub import AudioSegment
import matplotlib.pyplot as plt
from random import choice, randint, shuffle
from IPython.display import Audio, display
from tqdm import tqdm
import uuid
import torch
from transformers import Wav2Vec2Processor, Wav2Vec2Model
import torchaudio

import joblib
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

embeddings = embedder.create_embeddings(train_sample1)

speaker_pipeline = Pipeline([
    ('normalizer', StandardScaler()),
    ('cluster', KMeans(n_clusters=6))
])

# 3. Train and save entire pipeline
speaker_pipeline.fit(embeddings)

"""TRIANING ON MINI SPEECH"""

speaker_pipeline = Pipeline([
    ('normalizer', StandardScaler()),
    ('cluster', KMeans(n_clusters=6))
])

# 3. Train and save entire pipeline
speaker_pipeline.fit(embeddings)

joblib.dump(speaker_pipeline, '/content/speaker_pipeline.pkl')

"""# ----------- DIARIZATION PHASE (Load Full Pipeline) -----------"""

class SpeakerDiarizer:
    def __init__(self, pipeline_path, embedder, window_length=1.5, overlap=0.5):
        self.pipeline = joblib.load(pipeline_path)
        self.embedder = embedder
        self.window_length = window_length
        self.overlap = overlap
        self.sr = 16000
        self.label_map = {}

    def _time_to_samples(self, time):
        return int(time * self.sr)

    def process_audio(self, audio_path):
        """Core audio processing method that was missing"""
        # Load audio
        waveform, sample_rate = torchaudio.load(audio_path)
        waveform = torch.mean(waveform, dim=0) if waveform.dim() > 1 else waveform

        # Create segments
        window_samples = self._time_to_samples(self.window_length)
        hop_samples = self._time_to_samples(self.window_length - self.overlap)

        segments = []
        for start in range(0, waveform.shape[0], hop_samples):
            end = start + window_samples
            if end > waveform.shape[0]:
                break
            segment = waveform[start:end]
            segments.append({
                "start_time": start / sample_rate,
                "end_time": end / sample_rate,
                "waveform": segment.unsqueeze(0)
            })

        # Extract embeddings
        segment_embeddings = []
        for seg in segments:
            with torch.no_grad():
                emb = self.embedder.classifier.encode_batch(
                    seg["waveform"].to(self.embedder.device)
                )
                segment_embeddings.append(emb.squeeze().cpu().numpy())

        # Predict clusters
        X = np.array(segment_embeddings)
        if X.ndim == 1:
            X = X.reshape(1, -1)
        cluster_labels = self.pipeline.predict(X)

        # Assign cluster IDs
        for i, seg in enumerate(segments):
            seg["speaker_id"] = cluster_labels[i]

        return segments

    def _create_label_mapping(self, train_paths):
        """Create cluster to speaker mapping using training data"""
        train_embeddings = self.embedder.create_embeddings(train_paths)
        train_labels = self.pipeline.predict(train_embeddings)

        from collections import defaultdict
        cluster_speaker_map = defaultdict(list)

        for path, label in zip(train_paths, train_labels):
            speaker = path.split('/')[-2]
            cluster_speaker_map[label].append(speaker)

        for cluster, speakers in cluster_speaker_map.items():
            self.label_map[cluster] = max(set(speakers), key=speakers.count)

    def diarize(self, audio_path, train_paths):
        self._create_label_mapping(train_paths)
        segments = self.process_audio(audio_path)

        for seg in segments:
            cluster_id = seg["speaker_id"]
            seg["speaker_label"] = self.label_map.get(cluster_id, f"Unknown_{cluster_id}")

        return segments

"""# ----------- USAGE EXAMPLE -----------

"""

diarizer = SpeakerDiarizer(
    pipeline_path="/content/speaker_pipeline.pkl",
    embedder=embedder,
    window_length=1.5,
    overlap=0.5
)


test_file = "/content/minispeakerdiarization2/dataset/test/test_1.wav"
segments = diarizer.diarize(test_file, train_sample1)

print("\nSpeaker Diarization Results:")
print("Start Time\tEnd Time\tSpeaker ID")
for seg in segments:
    print(f"{seg['start_time']:.2f}\t{seg['end_time']:.2f}\t{seg['speaker_label']}")

print("\nSpeaker Diarization Results:")
print("Start Time\tEnd Time\tSpeaker ID")
for seg in segments:
    print(f"{seg['start_time']:.2f}\t{seg['end_time']:.2f}\t{seg['speaker_label']}")

"""# 💥 DER"""

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

!pip install pyannote.metrics

import os
from pyannote.metrics.diarization import DiarizationErrorRate
from pyannote.core import Annotation, Segment
from pyannote.core import notebook
from pyannote.database.util import load_rttm

TEST_DIR = "/content/minispeakerdiarization2/dataset/test"
REF_DIR = os.path.join(TEST_DIR, "rttm")
HYP_DIR = "/content/results"
os.makedirs(HYP_DIR, exist_ok=True)

def create_rttm(segments, audio_id, output_path):
    """Convert diarization results to RTTM format"""
    with open(output_path, 'w') as f:
        for seg in segments:
            start = seg['start_time']
            dur = seg['end_time'] - start
            line = f"SPEAKER {audio_id} 1 {start:.3f} {dur:.3f} <NA> <NA> {seg['speaker_label']} <NA> <NA>\n"
            f.write(line)

from os.path import basename, splitext

from pyannote.database.util import load_rttm
from pyannote.metrics.diarization import DiarizationErrorRate

reference_path  = '/content/minispeakerdiarization2/dataset/test/rttm/test_1.rttm'
hypothesis_path = '/content/results/test_1.rttm'


def load_annotation(rttm_path):
    uri = splitext(basename(rttm_path))[0]
    ann_dict = load_rttm(rttm_path)
    return ann_dict[uri]


reference  = load_annotation(reference_path)
hypothesis = load_annotation(hypothesis_path)

# 2. Initialize DER metric
metric = DiarizationErrorRate(collar=0.0, skip_overlap=False)

# 3. Compute DER
der_value = metric(reference, hypothesis)
print(f"Diarization Error Rate (DER): {der_value:.3f}")


components = metric(reference, hypothesis, detailed=True)
print("\nDetailed error (in seconds):")
for error_type, duration in components.items():
    print(f"  {error_type:15s}: {duration:.3f}")

from google.colab import files
uploaded = files.upload()

from IPython.display import Audio
from google.colab import files

uploaded = files.upload()

# Get the first uploaded filename from the dictionary keys
# Assuming the user uploads at least one file
if uploaded:
    audio_file = list(uploaded.keys())[0]
    Audio(audio_file)
else:
    print("No file was uploaded.")

Audio(audio_file)

import whisper
model = whisper.load_model("medium")
print("Whisper installed successfully!")

!whisper "/content/batman.wav"